# Generated by Django 2.2.7 on 2019-11-22 06:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('previous_id', models.UUIDField(default=uuid.uuid4)),
                ('image', models.ImageField(upload_to='image/')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('point_rate', models.IntegerField(blank=True, null=True)),
                ('line_rate', models.IntegerField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'road',
            },
        ),
    ]
