# Generated by Django 2.2.7 on 2019-11-17 23:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0002_road_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='road',
            old_name='rate',
            new_name='point_rate',
        ),
        migrations.AddField(
            model_name='road',
            name='line_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='road',
            name='previous_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
