# Generated by Django 2.2.7 on 2019-12-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0002_road_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='matching',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='road',
            name='prev_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='road',
            name='prev_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
