# Generated by Django 2.2.7 on 2019-11-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191115_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=True, verbose_name='superuser'),
        ),
    ]
